"""Generation of the statistics.md master report for the Git repository."""

import datetime
import os


def load_markdown_asset(filepath: str, fallback: str = "") -> str:
    """Load a Markdown file. Returns the fallback string if not found."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return fallback


def build_model_persistence_table(cfg) -> tuple[str, str]:
    """
    Check per model whether a persisted model was loaded.
    Returns (persist_status_text, model_persistence_table_md).
    """
    persist_enabled = cfg.model_persistence.enabled
    persist_dir = cfg.model_persistence.models_dir
    persist_status_text = "ENABLED" if persist_enabled else "DISABLED"

    model_status_rows = []
    for key in ["msm", "hmm", "lstm", "transformer"]:
        filename = getattr(cfg.model_persistence.files, key)
        filepath = os.path.join(persist_dir, filename)
        file_exists = os.path.exists(filepath)
        if persist_enabled and file_exists:
            status = "Loaded (persisted)"
        else:
            status = "Newly trained"
        model_status_rows.append(f"| {key.upper()} | `{filename}` | {status} |")

    model_persistence_table = "\n".join(
        [
            "| Model | File | Status |",
            "|:---|:---|:---|",
        ]
        + model_status_rows
    )

    return persist_status_text, model_persistence_table


def generate_statistics_report(cfg) -> str:
    """
    Reads all generated Markdown/PNG assets and builds the
    master document statistics.md from them.

    Loads all partial reports (EDA, evaluation, SORR, MCS, timing, etc.)
    and inserts them into a unified Markdown template.

    Returns the final Markdown string.
    """
    ASSETS_DIR = cfg.paths.assets_dir

    # Load all Markdown assets
    eda_desc_stats_md = load_markdown_asset(cfg.asset_path("eda_descriptive_stats"))
    eda_adf_tests_md = load_markdown_asset(cfg.asset_path("eda_adf_tests"))
    evaluation_table_md = load_markdown_asset(cfg.asset_path("evaluation_table"))
    performance_summary_md = load_markdown_asset(cfg.asset_path("performance_summary"))
    sorr_summary_md = load_markdown_asset(
        os.path.join(ASSETS_DIR, cfg.asset_path("sorr_summary"))
    )
    mcs_summary_md = load_markdown_asset(
        os.path.join(ASSETS_DIR, cfg.asset_path("mcs_summary"))
    )
    feature_corr_table_md = load_markdown_asset(cfg.asset_path("feature_correlation_table"))
    annualized_metrics_md = load_markdown_asset(
        cfg.asset_path("annualized_metrics"),
        fallback="*No annualized metrics available.*",
    )
    crisis_performance_md = load_markdown_asset(
        cfg.asset_path("crisis_performance"),
        fallback="*No crisis performance available.*",
    )

    # --- Issue #13: Extended Evaluation ---
    classification_md = load_markdown_asset(
        cfg.asset_path("classification_metrics"),
        fallback="*No classification metrics available.*",
    )
    churning_md = load_markdown_asset(
        cfg.asset_path("churning_stats"),
        fallback="*No churning statistics available.*",
    )
    depletion_ci_md = load_markdown_asset(
        cfg.asset_path("depletion_ci"),
        fallback="*No depletion CI available.*",
    )
    h1_md = load_markdown_asset(
        cfg.asset_path("h1_drawdown"),
        fallback="*H1 test not yet performed.*",
    )
    h2_md = load_markdown_asset(
        cfg.asset_path("h2_transformer"),
        fallback="*H2 test not yet performed.*",
    )
    break_even_md = load_markdown_asset(
        cfg.asset_path("break_even_table"),
        fallback="*No break-even analysis available.*",
    )
    withdrawal_sensitivity_md = load_markdown_asset(
        cfg.asset_path("withdrawal_sensitivity"),
        fallback="*No withdrawal rate sensitivity available.*",
    )
    switch_timing_md = load_markdown_asset(
        cfg.asset_path("switch_timing"),
        fallback="*No switch timing analysis available.*",
    )
    optuna_best_params_md = load_markdown_asset(
        cfg.asset_path("optuna_best_params"),
        fallback="*No Optuna optimization performed.*",
    )
    # Issue #5: post-HPO analysis assets (generated by /models/hpo-analysis)
    hpo_convergence_md = load_markdown_asset(
        cfg.asset_path("hpo_convergence"),
        fallback="*Convergence review not yet generated (run HPO analysis).*",
    )
    objective_sensitivity_md = load_markdown_asset(
        cfg.asset_path("objective_sensitivity"),
        fallback="*Objective sensitivity not yet generated (run HPO analysis).*",
    )
    hpo_dsr_md = load_markdown_asset(
        cfg.asset_path("hpo_dsr"),
        fallback="*DSR not yet generated (run HPO analysis with scope=full).*",
    )
    hpo_pbo_md = load_markdown_asset(
        cfg.asset_path("hpo_pbo"),
        fallback="*PBO not yet generated (run HPO analysis with scope=full).*",
    )
    hpo_multiseed_md = load_markdown_asset(
        cfg.asset_path("hpo_multiseed"),
        fallback="*Multi-seed reeval not yet generated (run HPO analysis with scope=full).*",
    )

    # Load threshold sensitivity per model
    threshold_models = list(cfg.evaluation.extended.f1_models)
    threshold_sections = []
    for m in threshold_models:
        md = load_markdown_asset(
            cfg.asset_path("threshold_sensitivity").replace("{model}", m),
            fallback=f"*No threshold sensitivity table available for {m}.*",
        )
        threshold_sections.append(f"**{m}**\n\n{md}")
    threshold_sensitivity_md = "\n\n".join(threshold_sections)

    # Load time-to-recovery per model (Buy_Hold + all f1_models)
    ttr_models = ["Buy_Hold"] + threshold_models
    ttr_sections = []
    for m in ttr_models:
        md = load_markdown_asset(
            cfg.asset_path("ttr_table").replace("{model}", m),
            fallback=f"*No time-to-recovery table available for {m}.*",
        )
        ttr_sections.append(f"**{m}**\n\n{md}")
    ttr_md = "\n\n".join(ttr_sections)

    # Read fast mode status from config
    fast_mode_enabled = cfg.fast_mode.enabled
    fast_mode_status = "TRUE (Development Mode)" if fast_mode_enabled else "FALSE (Full Run)"

    # Walk-forward status
    wf_enabled = getattr(cfg.walk_forward, "enabled", False)
    if wf_enabled:
        wf_status = (
            f"ENABLED (mode: {cfg.walk_forward.mode}, "
            f"train: {cfg.walk_forward.train_window_years}y, "
            f"test: {cfg.walk_forward.test_window_months}m, "
            f"step: {cfg.walk_forward.step_months}m)"
        )
    else:
        wf_status = "DISABLED (single 80/20 split)"

    # Model persistence status
    persist_status_text, model_persistence_table = build_model_persistence_table(cfg)
    persist_dir = cfg.model_persistence.models_dir

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    if cfg.data.end_date_is_frozen:
        data_window_note = (
            f"All evaluations are based on the **frozen dataset** "
            f"from **{cfg.data.start_date}** to **{cfg.data.end_date}** "
            f"(thesis freeze)."
        )
    else:
        data_window_note = (
            f"All evaluations are based on the dataset up to yesterday "
            f"({cfg.data.end_date}) and are updated automatically."
        )

    stats_md_content = f"""
# Detailed Statistical Evaluation & Research Results

This page documents the numerical and graphical results of the research pipeline. {data_window_note}

---

## 1. Executive Summary: Performance & Risk
A direct comparison of the core metrics over the entire **out-of-sample test period**.

{performance_summary_md}

> **Key point:** Compare the **max drawdown** of the active strategies with the buy-and-hold benchmark. The objective of this work is a significant reduction of this value to mitigate SORR.

---

## 2. Data Basis & Baseline Portfolio
The analysis is based on a global multi-asset approach.

### Exploratory Data Analysis (EDA)
**Descriptive statistics of the base time series:**
{eda_desc_stats_md}

**Stationarity check (augmented Dickey-Fuller test):**
{eda_adf_tests_md}

**Volatility clusters and autocorrelation (heteroskedasticity):**
![Volatility Clusters](../assets/{cfg.paths.assets.eda_volatility_clusters})

### Feature Correlation
Pearson correlation matrix of the six model features to check for multicollinearity.

![Feature Correlation Matrix](../assets/{cfg.paths.assets.feature_correlation_matrix})

### SORR Context: Historical Drawdowns
The most extreme loss phases of the 60/40 portfolio, shown as motivation for active capital protection.
![Historical Drawdowns](../assets/{cfg.paths.assets.eda_historical_drawdowns})

### 60/40 Portfolio Capital Curve
The figure shows the cumulative performance of the static reference portfolio (60% equities / 40% bonds).

![Capital Curve](../assets/{cfg.paths.assets.capital_curve})

*   **Data source:** S&P 500 (`^GSPC`) and Vanguard Long-Term Treasury (`VUSTX`).
*   **Reproducibility:** The cleaned dataset incl. all features is stored at: `data/02_feature_engineered_data.parquet`.

---

## 3. Regime Detection of the Individual Models
This section visualizes the identification results of the model categories (statistics, clustering, deep learning).

### A. Markov-Switching Models (Econometrics)
Identification of bull and bear regimes using a univariate two-regime Markov-switching model based on S&P 500 returns.
![Markov Models](../assets/{cfg.paths.assets.markov_model})

### B. Hidden Markov Model (Unsupervised Clustering)
![HMM Regimes](../assets/{cfg.paths.assets.hmm_regimes})

### C. Univariate HMM (Ablation, Issue #3)
Robustness check for the MSM-vs-HMM architecture comparison: identical
input space to the MSM (60/40 returns only). Isolates the architectural effect
(clustering vs. Markov-switching regression) from the information contribution of the
extended features (VIX, yield spread).
![HMM Uni Regimes](../assets/{cfg.paths.assets.hmm_uni_regimes})

### D. LSTM Network (Deep Learning)
Prediction of market phases by the neural network (trained on Pagan-Sossounov labels).
![LSTM Model](../assets/{cfg.paths.assets.lstm_model})

### E. Transformer Network (Attention-Based Regime Detection)
Classification of market regimes using a Transformer encoder with multi-head self-attention and positional encoding. In contrast to recurrent architectures (LSTM), the Transformer processes all time steps of a sequence in parallel and learns via the attention mechanism which historical data points are most relevant for the current regime classification. Trained in a supervised setting on Pagan-Sossounov labels.
![Transformer Model](../assets/{cfg.paths.assets.transformer_model})

### F. Global Regime Comparison
Detailed comparison of the probabilities and hard signals of all models.
![Regime Comparison](../assets/{cfg.paths.assets.regime_comparison})

### G. Hyperparameter Optimization (Optuna)
Search over the hyperparameter space of all models using walk-forward validation as inner CV. The objective is the configured risk metric (default: Martin ratio = CAGR / Ulcer index) on the **pooled** OOS return series across all HPO folds. Econometric models are searched exhaustively via GridSampler, the DL models via a multivariate TPESampler. Selection runs on the development folds only (`tune_until`); the holdout folds stay selection-free for the final walk-forward run. The values reported here were adopted into `config.yaml` for the final run.

{optuna_best_params_md}

**Diagnostic plots per model** (optimization history, parameter importance, slice, contour):

| Model | History | Importance | Slice | Contour |
|:---|:---|:---|:---|:---|
| MSM         | ![](../assets/optuna_MSM_history.png)         | ![](../assets/optuna_MSM_importance.png)         | ![](../assets/optuna_MSM_slice.png)         | n/a ¹                                         |
| HMM         | ![](../assets/optuna_HMM_history.png)         | ![](../assets/optuna_HMM_importance.png)         | ![](../assets/optuna_HMM_slice.png)         | ![](../assets/optuna_HMM_contour.png)         |
| HMM_Uni     | ![](../assets/optuna_HMM_Uni_history.png)     | ![](../assets/optuna_HMM_Uni_importance.png)     | ![](../assets/optuna_HMM_Uni_slice.png)     | n/a ¹                                         |
| LSTM        | ![](../assets/optuna_LSTM_history.png)        | ![](../assets/optuna_LSTM_importance.png)        | ![](../assets/optuna_LSTM_slice.png)        | ![](../assets/optuna_LSTM_contour.png)        |
| Transformer | ![](../assets/optuna_Transformer_history.png) | ![](../assets/optuna_Transformer_importance.png) | ![](../assets/optuna_Transformer_slice.png) | ![](../assets/optuna_Transformer_contour.png) |

¹ MSM and HMM_Uni have only one hyperparameter (`threshold`) in the search space. The contour plot would be degenerate and is omitted.

#### G.1 Convergence & Edge-of-Range Review
Best value and trial, fANOVA importance, and a flag for optima sitting within one grid step of a search bound (indicating the range may be too narrow).

{hpo_convergence_md}

#### G.2 Objective Sensitivity
Which config would have been selected under each candidate metric, valued across all metrics. `same_as_objective = True` throughout means the model choice is robust to the objective; divergences quantify the trade-off.

{objective_sensitivity_md}

#### G.3 Deflated Sharpe Ratio & Backtest Overfitting
DSR deflates the selected config's Sharpe for the number of tested configs; PBO (CSCV) estimates the probability that the in-sample-best config underperforms out-of-sample.

{hpo_dsr_md}

{hpo_pbo_md}

#### G.4 Multi-Seed Robustness (DL)
Top DL configs re-evaluated over several global seeds; mean/std of every metric quantify seed sensitivity of the deep-learning ranking.

{hpo_multiseed_md}

### H. Label Concordance (Selection of the Training Labels)
Comparison of the regime labelers (MSM, HMM, Pagan-Sossounov, Peak-to-Trough, Lunde-Timmermann, NBER) to justify the label choice for the supervised models. Pagan-Sossounov was chosen as the training target for LSTM and Transformer due to its high concordance with NBER recession periods.

![Label Concordance](../assets/{cfg.paths.assets.label_concordance_matrix})
![Label Cohen's κ](../assets/{cfg.paths.assets.label_kappa_matrix})
![Label Timeline](../assets/{cfg.paths.assets.label_timeline_comparison})

---

## 4. Backtesting & Strategy Evaluation
The economic application of the regime signals via dynamic reallocation into the money market.

### Walk-Forward Schema
Rolling train/test windows over the entire study period. Each row corresponds to one fold; the blue bar marks the training window, the orange bar the OOS test window. The strict chronological separation prevents look-ahead bias.

![Walk-Forward Schema](../assets/{cfg.paths.assets.walk_forward_schema})

### Equity Curves in Comparison
![Equity Curves](../assets/{cfg.paths.assets.equity_curves})

### Annualized Performance Metrics
Normalized metrics (CAGR, Sharpe, Sortino, Calmar) for comparison across evaluation periods of different lengths.

{annualized_metrics_md}

### Classification Metrics (vs. NBER Recessions as Ground Truth)
Comparison of the models as binary recession classifiers (precision, recall, F1).

{classification_md}

![Confusion Matrices](../assets/{cfg.paths.assets.confusion_matrices})

**ROC and precision-recall curves** (threshold-independent comparison via `*_Prob`):

![ROC Curves](../assets/{cfg.paths.assets.roc_curves})
![PR Curves](../assets/{cfg.paths.assets.pr_curves})

### Signal Churning & Whipsaw Analysis
Quantification of the switching frequency and the share of very short regime phases ("whipsaws").

{churning_md}

### Regime Probability Heatmap
Bear probabilities of all models over time.

![Regime Probability Heatmap](../assets/{cfg.paths.assets.regime_probability_heatmap})

### Threshold Sensitivity
Variation of the decision threshold per model. Shows how robust final wealth, max drawdown, and the number of regime switches are to a modified bull/bear classification boundary (thesis ch. 4.1, smoothing).

{threshold_sensitivity_md}

### Time-to-Recovery
All drawdown phases beyond the minimum depth (per `extended.ttr_min_dd`) with peak, trough, and recovery date as well as duration in trading days. An open (not yet recovered) phase is marked as "open" in the recovery field.

{ttr_md}

### Crisis Performance
Return and max drawdown during historical crisis periods: the central evidence for the tail-risk protection of the regime-switching models.

{crisis_performance_md}

### Switch Timing Relative to the Drawdown Peak
Time lag between the model's first bear signal and the drawdown trough of the buy-and-hold portfolio per crisis. Positive = model reacted early, negative = too late.

{switch_timing_md}

### Drawdown Profile
![Drawdown](../assets/{cfg.paths.assets.drawdown})

### Rolling Sharpe Ratio
Time-varying, risk-adjusted return comparison over a rolling 252-day window.

![Rolling Sharpe](../assets/{cfg.paths.assets.rolling_sharpe})

### Comprehensive Metrics Matrix
Detailed statistical analysis including risk-adjusted metrics (Sharpe, Sortino, Calmar).

{evaluation_table_md}

### Transaction Costs

This figure shows the cumulative transaction costs over time. Steep increases indicate unstable regime switches ("churning").

![Transaction Costs](../assets/{cfg.paths.assets.transaction_costs})

Stress test: Sequence of Returns Risk (SORR)
In addition, the survival time of the capital was simulated in a withdrawal phase (retirement scenario).

### SORR Simulation: Comparison of the Withdrawal Scenarios

This table compares different stress scenarios (standard, aggressive, low capital).

{sorr_summary_md}

Capital development of the different scenarios:
![SORR Standard](../assets/{cfg.paths.assets.sorr_sim_standard})
![SORR Aggressive](../assets/{cfg.paths.assets.sorr_sim_aggressive})
![SORR Low Capital](../assets/{cfg.paths.assets.sorr_sim_low_capital})

### MCS: Block-Bootstrap Robustness Check

To assess statistical significance, 10,000 artificial market paths were simulated via block bootstrap.
![MCS Paths](../assets/{cfg.paths.assets.mcs_paths})
{mcs_summary_md}

Distribution of the terminal capital values:

![MCS Boxplots Standard](../assets/{cfg.paths.assets.mcs_boxplot_standard})
![MCS Boxplots Aggressive](../assets/{cfg.paths.assets.mcs_boxplot_aggressive})
![MCS Boxplots Low Capital](../assets/{cfg.paths.assets.mcs_boxplot_low_capital})

Probability corridors:

The shaded areas show the 5% to 95% confidence interval of the capital development.
![MCS Quantiles](../assets/{cfg.paths.assets.mcs_quantiles})

### Depletion Rate with 95% Confidence Interval
Wilson CI for the ruin probability (P[terminal capital ≤ 0]) per scenario × strategy.

{depletion_ci_md}

### Hypothesis Tests (Paired Wilcoxon, α = 0.05)
**H1: Regime switching reduces MaxDD vs. buy and hold:**

{h1_md}

**H2: The Transformer dominates econometrics and LSTM in terminal wealth:**

{h2_md}

### Break-Even Transaction Costs
At what cost rate (in basis points per reallocation) does active switching lose its return advantage over buy and hold?

{break_even_md}

![Break-Even Analysis](../assets/{cfg.paths.assets.break_even_plot})

### Withdrawal Rate Sensitivity (3.5% / 4% / 5%)
Robustness of the SORR results under varying annual withdrawals.

{withdrawal_sensitivity_md}

---

## Research Notes & Methodology
- **Cash component:** On a "bear" signal, the strategy reallocates into the current money market rate (**^IRX**).
- **Look-ahead bias prevention:** All signals are shifted by one day for the backtesting (`shift(1)`) to simulate real trading conditions.
- **Feature set:** The models use returns, volatility (20d), SMA distance, momentum, VIX, and yield spread.
- **Cost simulation:** A flat fee of 10 basis points (0.1%) is charged per reallocation.
- **SORR specifics:** For withdrawals during "bull" phases, an additional liquidity fee of 0.1% is charged on the withdrawal amount (asset sales). In "bear" phases (cash), this fee does not apply.

---

## Model Persistence

Model persistence status for this pipeline run:

- **Persistence:** {persist_status_text}
- **Model directory:** `{persist_dir}`

{model_persistence_table}

> **Note:** With persistence enabled, pre-trained models are loaded from `{persist_dir}` if the files exist. Otherwise, training runs normally and the result is stored for future runs. When hyperparameters change, the corresponding model files must be deleted.

---

**Last updated:** {timestamp}<br>
**End date:** `{cfg.data.end_date}`<br>
**Fast mode status at runtime:** {fast_mode_status}<br>
**Walk-forward validation:** {wf_status}<br>
**Model persistence:** {persist_status_text}<br>
*Generated by the Backtest Service (reporting).*
"""

    return stats_md_content
